server:
  port: "${PORT:8099}"

spring:
  datasource:
    url: "${DB_URL:jdbc:mysql://localhost:33061/daoyun}"
    username: "${DB_USER:root}"
    password: "${DB_PASS:password}"

  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create
      # ddl-auto: none
      # ddl-auto: create-drop # DEV

redis:
  host: "${REDIS_HOST:localhost}"
  port: "${REDIS_PORT:63791}"
  password: "${REDIS_PASS:password}"

logging:
  level:
    root: INFO

jwt:
  secret: "${JWT_SECRET:helloworld}"
  aliveTimeFrame_second: 1800

# using environment variable
# AliyunAccessKeyId: 
# AliyunAccessKeySecret: 

daoyun:
  supersuper:
    enable: false
    name: daoyun
  message:
    enable: true
    waitMs: 6000
    validMs: 300000
  reset:
    validMs: 300000
  aliyun:
    AliyunSmsSignName: "${ALIYUN_SMS_SIGN_NAME:生意专家}"
    TemplateCode:
      login:  "${SMS_LOGIN_TEMPLATE_CODE:SMS_205462496}"
      signup: "${SMS_SIGNUP_TEMPLATE_CODE:SMS_205462496}"
      reset:  "${SMS_RESET_TEMPLATE_CODE:SMS_205462496}"
      bindPhoneNum: "${SMS_BIND_PHONE_TEMPLATE_CODE:SMS_205462496}"
  hcaptcha:
    allowNum: 30
    retainS: 300
    endpoint: https://hcaptcha.com/siteverify
    sitesecret: '0x77CFb863E1Fceb0139Ccd56dB08ffEA6584C67A6'

